module.exports = {

	CRLF: '\r\n',

	RequestHeaders: [
        'accept',
        'accept-charset',
        'accept-encoding',
        'accept-language',
        'accept-datetime',
        'authorization',
        'cache-control',
        'connection',
        'cookie',
        'content-length',
        'content-md5',
        'content-type',
        'date',
        'expect',
        'forwarded',
        'from',
        'host',
        'if-match',
        'if-modified-since',
        'if-none-match',
        'if-range',
        'if-unmodified-since',
        'max-forwards',
        'origin',
        'pragma',
        'proxy-authorization',
        'range',
        'referer',
        'te',
        'user-agent',
        'upgrade',
        'via',
        'warning'
	],

	ResponseHeaders: [
		'cache-control',
		'connection',
		'date',
		'pragma',
		'trailer',
		'transfer-encoding',
		'upgrade',
		'via',
		'warning',
		'allow',
		'content-encoding',
		'content-language',
		'content-length',
		'content-location',
		'content-md5',
		'content-range',
		'content-type',
		'expires',
		'last-modified',
		'accept-ranges',
		'age',
		'etag',
		'location',
		'proxy-authenticate',
		'retry-after',
		'server',
		'vary',
		'www-authenticate'
	],

	StatusCodes: {
		'Continue': '100',
		'Switching Protocols': '101',
		'OK': '200',
		'Created': '201',
		'Accepted': '202',
		'Non-Authoritative Information': '203',
		'No Content': '204',
		'Reset Content': '205',
		'Partial Content': '206',
		'Multiple Choices': '300',
		'Moved Permanently': '301',
		'Found': '302',
		'See Other': '303',
		'Not Modified': '304',
		'Use Proxy': '305',
		'Temporary Redirect': '307',
		'Bad Request': '400',
		'Unauthorized': '401',
		'Payment Required': '402',
		'Forbidden': '403',
		'Not Found': '404',
		'Method Not Allowed': '405',
		'Not Acceptable': '406',
		'Proxy Authentication Required': '407',
		'Request Time-out': '408',
		'Conflict': '409',
		'Gone': '410',
		'Length Required': '411',
		'Precondition Failed': '412',
		'Request Entity Too Large': '413',
		'Request-URI Too Large': '414',
		'Unsupported Media Type': '415',
		'Requested range not satisfiable': '416',
		'Expectation Failed': '417',
		'Internal Server Error': '500',
		'Not Implemented': '501',
		'Bad Gateway': '502',
		'Service Unavailable': '503',
		'Gateway Time-out': '504',
		'HTTP Version not supported': '505',

        100: 'Continue',
        101: 'Switching Protocols',
        200: 'OK',
        201: 'Created',
        202: 'Accepted',
        203: 'Non-Authoritative Information',
        204: 'No Content',
        205: 'Reset Content',
        206: 'Partial Content',
        300: 'Multiple Choices',
        301: 'Moved Permanently',
        302: 'Found',
        303: 'See Other',
        304: 'Not Modified',
        305: 'Use Proxy',
        307: 'Temporary Redirect',
        400: 'Bad Request',
        401: 'Unauthorized',
        402: 'Payment Required',
        403: 'Forbidden',
        404: 'Not Found',
        405: 'Method Not Allowed',
        406: 'Not Acceptable',
        407: 'Proxy Authentication Required',
        408: 'Request Time-out',
        409: 'Conflict',
        410: 'Gone',
        411: 'Length Required',
        412: 'Precondition Failed',
        413: 'Request Entity Too Large',
        414: 'Request-URI Too Large',
        415: 'Unsupported Media Type',
        416: 'Requested range not satisfiable',
        417: 'Expectation Failed',
        500: 'Internal Server Error',
        501: 'Not Implemented',
        502: 'Bad Gateway',
        503: 'Service Unavailable',
        504: 'Gateway Time-out',
        505: 'HTTP Version not supported'
	},

	Methods: [
		'GET',
		'POST',
		'PUT',
		'DELETE',
		'OPTIONS',
		'TRACE'
	]
}